In [49]:
import pandas as pd
import requests
from sqlalchemy import create_engine

url='https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&past_days=10&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m'
response = requests.get(url)

print(response.status_code)

200

In [50]:
response.headers["content-type"]

'application/json; charset=utf-8'

In [51]:
data=response.json()
data

{'latitude': 52.52,
 'longitude': 13.419998,
 'generationtime_ms': 3.0955076217651367,
 'utc_offset_seconds': 0,
 'timezone': 'GMT',
 'timezone_abbreviation': 'GMT',
 'elevation': 38.0,
 'hourly_units': {'time': 'iso8601',
  'temperature_2m': '°C',
  'relative_humidity_2m': '%',
  'wind_speed_10m': 'km/h'},
 'hourly': {'time': ['2026-08-30T00:00',
   '2026-08-30T01:00',
   '2026-08-30T02:00',
   '2026-08-30T03:00',
   '2026-08-30T04:00',
   '2026-08-30T05:00',
   '2026-08-30T06:00',
   '2026-08-30T07:00',
   '2026-08-30T08:00',
   '2026-08-30T09:00',
   '2026-08-30T10:00',
   '2026-08-30T11:00',
   '2026-08-30T12:00',
   '2026-08-30T13:00',
   '2026-08-30T14:00',
   '2026-08-30T15:00',
   '2026-08-30T16:00',
   '2026-08-30T17:00',
   '2026-08-30T18:00',
   '2026-08-30T19:00',
   '2026-08-30T20:00',
   '2026-08-30T21:00',
   '2026-08-30T22:00',
   '2026-08-30T23:00',
   '2026-08-31T00:00',
   '2026-08-31T01:00',
   '2026-08-31T02:00',
   '2026-08-31T03:00',
   '2026-08-31T04:00',
   '2026-08-31T05:00',
   '2026-08-31T06:00',
   '2026-08-31T07:00',
   '2026-08-31T08:00',
   '2026-08-31T09:00',
   '2026-08-31T10:00',
   '2026-08-31T11:00',
   '2026-08-31T12:00',
   '2026-08-31T13:00',
   '2026-08-31T14:00',
   '2026-08-31T15:00',
   '2026-08-31T16:00',
   '2026-08-31T17:00',
   '2026-08-31T18:00',
   '2026-08-31T19:00',
   '2026-08-31T20:00',
   '2026-08-31T21:00',
   '2026-08-31T22:00',
   '2026-08-31T23:00',
   '2026-09-01T00:00',
   '2026-09-01T01:00',
   '2026-09-01T02:00',
   '2026-09-01T03:00',
   '2026-09-01T04:00',
   '2026-09-01T05:00',
   '2026-09-01T06:00',
   '2026-09-01T07:00',
   '2026-09-01T08:00',
   '2026-09-01T09:00',
   '2026-09-01T10:00',
   '2026-09-01T11:00',
   '2026-09-01T12:00',
   '2026-09-01T13:00',
   '2026-09-01T14:00',
   '2026-09-01T15:00',
   '2026-09-01T16:00',
   '2026-09-01T17:00',
   '2026-09-01T18:00',
   '2026-09-01T19:00',
   '2026-09-01T20:00',
   '2026-09-01T21:00',
   '2026-09-01T22:00',
   '2026-09-01T23:00',
   '2026-09-02T00:00',
   '2026-09-02T01:00',
   '2026-09-02T02:00',
   '2026-09-02T03:00',
   '2026-09-02T04:00',
   '2026-09-02T05:00',
   '2026-09-02T06:00',
   '2026-09-02T07:00',
   '2026-09-02T08:00',
   '2026-09-02T09:00',
   '2026-09-02T10:00',
   '2026-09-02T11:00',
   '2026-09-02T12:00',
   '2026-09-02T13:00',
   '2026-09-02T14:00',
   '2026-09-02T15:00',
   '2026-09-02T16:00',
   '2026-09-02T17:00',
   '2026-09-02T18:00',
   '2026-09-02T19:00',
   '2026-09-02T20:00',
   '2026-09-02T21:00',
   '2026-09-02T22:00',
   '2026-09-02T23:00',
   '2026-09-03T00:00',
   '2026-09-03T01:00',
   '2026-09-03T02:00',
   '2026-09-03T03:00',
   '2026-09-03T04:00',
   '2026-09-03T05:00',
   '2026-09-03T06:00',
   '2026-09-03T07:00',
   '2026-09-03T08:00',
   '2026-09-03T09:00',
   '2026-09-03T10:00',
   '2026-09-03T11:00',
   '2026-09-03T12:00',
   '2026-09-03T13:00',
   '2026-09-03T14:00',
   '2026-09-03T15:00',
   '2026-09-03T16:00',
   '2026-09-03T17:00',
   '2026-09-03T18:00',
   '2026-09-03T19:00',
   '2026-09-03T20:00',
   '2026-09-03T21:00',
   '2026-09-03T22:00',
   '2026-09-03T23:00',
   '2026-09-04T00:00',
   '2026-09-04T01:00',
   '2026-09-04T02:00',
   '2026-09-04T03:00',
   '2026-09-04T04:00',
   '2026-09-04T05:00',
   '2026-09-04T06:00',
   '2026-09-04T07:00',
   '2026-09-04T08:00',
   '2026-09-04T09:00',
   '2026-09-04T10:00',
   '2026-09-04T11:00',
   '2026-09-04T12:00',
   '2026-09-04T13:00',
   '2026-09-04T14:00',
   '2026-09-04T15:00',
   '2026-09-04T16:00',
   '2026-09-04T17:00',
   '2026-09-04T18:00',
   '2026-09-04T19:00',
   '2026-09-04T20:00',
   '2026-09-04T21:00',
   '2026-09-04T22:00',
   '2026-09-04T23:00',
   '2026-09-05T00:00',
   '2026-09-05T01:00',
   '2026-09-05T02:00',
   '2026-09-05T03:00',
   '2026-09-05T04:00',
   '2026-09-05T05:00',
   '2026-09-05T06:00',
   '2026-09-05T07:00',
   '2026-09-05T08:00',
   '2026-09-05T09:00',
   '2026-09-05T10:00',
   '2026-09-05T11:00',
   '2026-09-05T12:00',
   '2026-09-05T13:00',
   '2026-09-05T14:00',
   '2026-09-05T15:00',
   '2026-09-05T16:00',
   '2026-09-05T17:00',
   '2026-09-05T18:00',
   '2026-09-05T19:00',
   '2026-09-05T20:00',
   '2026-09-05T21:00',
   '2026-09-05T22:00',
   '2026-09-05T23:00',
   '2026-09-06T00:00',
   '2026-09-06T01:00',
   '2026-09-06T02:00',
   '2026-09-06T03:00',
   '2026-09-06T04:00',
   '2026-09-06T05:00',
   '2026-09-06T06:00',
   '2026-09-06T07:00',
   '2026-09-06T08:00',
   '2026-09-06T09:00',
   '2026-09-06T10:00',
   '2026-09-06T11:00',
   '2026-09-06T12:00',
   '2026-09-06T13:00',
   '2026-09-06T14:00',
   '2026-09-06T15:00',
   '2026-09-06T16:00',
   '2026-09-06T17:00',
   '2026-09-06T18:00',
   '2026-09-06T19:00',
   '2026-09-06T20:00',
   '2026-09-06T21:00',
   '2026-09-06T22:00',
   '2026-09-06T23:00',
   '2026-09-07T00:00',
   '2026-09-07T01:00',
   '2026-09-07T02:00',
   '2026-09-07T03:00',
   '2026-09-07T04:00',
   '2026-09-07T05:00',
   '2026-09-07T06:00',
   '2026-09-07T07:00',
   '2026-09-07T08:00',
   '2026-09-07T09:00',
   '2026-09-07T10:00',
   '2026-09-07T11:00',
   '2026-09-07T12:00',
   '2026-09-07T13:00',
   '2026-09-07T14:00',
   '2026-09-07T15:00',
   '2026-09-07T16:00',
   '2026-09-07T17:00',
   '2026-09-07T18:00',
   '2026-09-07T19:00',
   '2026-09-07T20:00',
   '2026-09-07T21:00',
   '2026-09-07T22:00',
   '2026-09-07T23:00',
   '2026-09-08T00:00',
   '2026-09-08T01:00',
   '2026-09-08T02:00',
   '2026-09-08T03:00',
   '2026-09-08T04:00',
   '2026-09-08T05:00',
   '2026-09-08T06:00',
   '2026-09-08T07:00',
   '2026-09-08T08:00',
   '2026-09-08T09:00',
   '2026-09-08T10:00',
   '2026-09-08T11:00',
   '2026-09-08T12:00',
   '2026-09-08T13:00',
   '2026-09-08T14:00',
   '2026-09-08T15:00',
   '2026-09-08T16:00',
   '2026-09-08T17:00',
   '2026-09-08T18:00',
   '2026-09-08T19:00',
   '2026-09-08T20:00',
   '2026-09-08T21:00',
   '2026-09-08T22:00',
   '2026-09-08T23:00',
   '2026-09-09T00:00',
   '2026-09-09T01:00',
   '2026-09-09T02:00',
   '2026-09-09T03:00',
   '2026-09-09T04:00',
   '2026-09-09T05:00',
   '2026-09-09T06:00',
   '2026-09-09T07:00',
   '2026-09-09T08:00',
   '2026-09-09T09:00',
   '2026-09-09T10:00',
   '2026-09-09T11:00',
   '2026-09-09T12:00',
   '2026-09-09T13:00',
   '2026-09-09T14:00',
   '2026-09-09T15:00',
   '2026-09-09T16:00',
   '2026-09-09T17:00',
   '2026-09-09T18:00',
   '2026-09-09T19:00',
   '2026-09-09T20:00',
   '2026-09-09T21:00',
   '2026-09-09T22:00',
   '2026-09-09T23:00',
   '2026-09-10T00:00',
   '2026-09-10T01:00',
   '2026-09-10T02:00',
   '2026-09-10T03:00',
   '2026-09-10T04:00',
   '2026-09-10T05:00',
   '2026-09-10T06:00',
   '2026-09-10T07:00',
   '2026-09-10T08:00',
   '2026-09-10T09:00',
   '2026-09-10T10:00',
   '2026-09-10T11:00',
   '2026-09-10T12:00',
   '2026-09-10T13:00',
   '2026-09-10T14:00',
   '2026-09-10T15:00',
   '2026-09-10T16:00',
   '2026-09-10T17:00',
   '2026-09-10T18:00',
   '2026-09-10T19:00',
   '2026-09-10T20:00',
   '2026-09-10T21:00',
   '2026-09-10T22:00',
   '2026-09-10T23:00',
   '2026-09-11T00:00',
   '2026-09-11T01:00',
   '2026-09-11T02:00',
   '2026-09-11T03:00',
   '2026-09-11T04:00',
   '2026-09-11T05:00',
   '2026-09-11T06:00',
   '2026-09-11T07:00',
   '2026-09-11T08:00',
   '2026-09-11T09:00',
   '2026-09-11T10:00',
   '2026-09-11T11:00',
   '2026-09-11T12:00',
   '2026-09-11T13:00',
   '2026-09-11T14:00',
   '2026-09-11T15:00',
   '2026-09-11T16:00',
   '2026-09-11T17:00',
   '2026-09-11T18:00',
   '2026-09-11T19:00',
   '2026-09-11T20:00',
   '2026-09-11T21:00',
   '2026-09-11T22:00',
   '2026-09-11T23:00',
   '2026-09-12T00:00',
   '2026-09-12T01:00',
   '2026-09-12T02:00',
   '2026-09-12T03:00',
   '2026-09-12T04:00',
   '2026-09-12T05:00',
   '2026-09-12T06:00',
   '2026-09-12T07:00',
   '2026-09-12T08:00',
   '2026-09-12T09:00',
   '2026-09-12T10:00',
   '2026-09-12T11:00',
   '2026-09-12T12:00',
   '2026-09-12T13:00',
   '2026-09-12T14:00',
   '2026-09-12T15:00',
   '2026-09-12T16:00',
   '2026-09-12T17:00',
   '2026-09-12T18:00',
   '2026-09-12T19:00',
   '2026-09-12T20:00',
   '2026-09-12T21:00',
   '2026-09-12T22:00',
   '2026-09-12T23:00',
   '2026-09-13T00:00',
   '2026-09-13T01:00',
   '2026-09-13T02:00',
   '2026-09-13T03:00',
   '2026-09-13T04:00',
   '2026-09-13T05:00',
   '2026-09-13T06:00',
   '2026-09-13T07:00',
   '2026-09-13T08:00',
   '2026-09-13T09:00',
   '2026-09-13T10:00',
   '2026-09-13T11:00',
   '2026-09-13T12:00',
   '2026-09-13T13:00',
   '2026-09-13T14:00',
   '2026-09-13T15:00',
   '2026-09-13T16:00',
   '2026-09-13T17:00',
   '2026-09-13T18:00',
   '2026-09-13T19:00',
   '2026-09-13T20:00',
   '2026-09-13T21:00',
   '2026-09-13T22:00',
   '2026-09-13T23:00',
   '2026-09-14T00:00',
   '2026-09-14T01:00',
   '2026-09-14T02:00',
   '2026-09-14T03:00',
   '2026-09-14T04:00',
   '2026-09-14T05:00',
   '2026-09-14T06:00',
   '2026-09-14T07:00',
   '2026-09-14T08:00',
   '2026-09-14T09:00',
   '2026-09-14T10:00',
   '2026-09-14T11:00',
   '2026-09-14T12:00',
   '2026-09-14T13:00',
   '2026-09-14T14:00',
   '2026-09-14T15:00',
   '2026-09-14T16:00',
   '2026-09-14T17:00',
   '2026-09-14T18:00',
   '2026-09-14T19:00',
   '2026-09-14T20:00',
   '2026-09-14T21:00',
   '2026-09-14T22:00',
   '2026-09-14T23:00',
   '2026-09-15T00:00',
   '2026-09-15T01:00',
   '2026-09-15T02:00',
   '2026-09-15T03:00',
   '2026-09-15T04:00',
   '2026-09-15T05:00',
   '2026-09-15T06:00',
   '2026-09-15T07:00',
   '2026-09-15T08:00',
   '2026-09-15T09:00',
   '2026-09-15T10:00',
   '2026-09-15T11:00',
   '2026-09-15T12:00',
   '2026-09-15T13:00',
   '2026-09-15T14:00',
   '2026-09-15T15:00',
   '2026-09-15T16:00',
   '2026-09-15T17:00',
   '2026-09-15T18:00',
   '2026-09-15T19:00',
   '2026-09-15T20:00',
   '2026-09-15T21:00',
   '2026-09-15T22:00',
   '2026-09-15T23:00'],
  'temperature_2m': [20.0,
   19.8,
   19.5,
   19.3,
   19.3,
   19.3,
   19.4,
   20.8,
   22.0,
   24.1,
   25.4,
   25.5,
   26.2,
   26.0,
   25.9,
   26.0,
   25.2,
   24.5,
   23.5,
   22.9,
   21.9,
   21.1,
   20.6,
   20.1,
   18.8,
   18.3,
   17.9,
   16.9,
   16.9,
   17.0,
   17.4,
   17.4,
   16.9,
   17.5,
   20.0,
   22.7,
   23.9,
   24.0,
   24.1,
   25.1,
   25.1,
   22.3,
   20.1,
   19.1,
   17.8,
   17.2,
   17.0,
   16.7,
   16.3,
   16.1,
   16.0,
   16.1,
   16.0,
   16.1,
   16.4,
   17.3,
   18.1,
   18.5,
   19.7,
   21.2,
   22.2,
   22.3,
   22.8,
   23.1,
   23.2,
   22.5,
   21.3,
   20.1,
   19.0,
   18.4,
   17.5,
   17.0,
   16.4,
   15.8,
   15.2,
   14.5,
   14.3,
   14.1,
   14.3,
   15.5,
   16.8,
   18.5,
   19.9,
   21.1,
   21.4,
   21.4,
   21.5,
   21.9,
   21.3,
   19.2,
   19.7,
   19.0,
   18.5,
   17.5,
   17.0,
   16.7,
   16.0,
   15.6,
   15.2,
   15.2,
   15.0,
   14.9,
   15.1,
   15.5,
   16.8,
   18.8,
   19.4,
   19.7,
   21.7,
   23.1,
   23.4,
   22.8,
   21.5,
   21.5,
   20.0,
   19.6,
   19.2,
   19.4,
   19.1,
   18.7,
   18.7,
   18.7,
   19.0,
   18.8,
   18.6,
   18.2,
   18.3,
   19.3,
   20.7,
   22.0,
   22.6,
   23.9,
   24.3,
   24.4,
   24.8,
   21.5,
   20.8,
   19.9,
   18.0,
   17.8,
   17.9,
   17.4,
   17.4,
   17.0,
   16.8,
   16.5,
   16.2,
   15.7,
   15.3,
   15.0,
   15.3,
   16.1,
   17.3,
   18.6,
   19.2,
   19.7,
   19.7,
   20.1,
   19.8,
   16.4,
   17.2,
   17.3,
   16.9,
   16.3,
   15.7,
   15.6,
   15.3,
   14.9,
   14.7,
   14.3,
   13.8,
   13.5,
   13.2,
   13.0,
   13.3,
   14.0,
   15.2,
   16.8,
   17.9,
   18.5,
   18.7,
   19.4,
   20.0,
   19.8,
   20.1,
   19.5,
   18.8,
   18.2,
   17.1,
   15.4,
   14.7,
   14.2,
   13.3,
   13.2,
   13.2,
   12.6,
   12.4,
   12.2,
   12.5,
   13.6,
   15.0,
   17.0,
   17.3,
   16.6,
   16.0,
   16.9,
   18.3,
   20.2,
   19.8,
   19.6,
   19.3,
   18.4,
   17.6,
   16.8,
   16.4,
   16.3,
   15.8,
   15.4,
   15.3,
   14.9,
   15.1,
   15.4,
   15.9,
   17.6,
   19.6,
   22.4,
   24.2,
   25.8,
   26.7,
   27.4,
   28.1,
   28.5,
   28.2,
   27.5,
   26.4,
   24.6,
   23.4,
   22.3,
   21.5,
   21.1,
   21.4,
   21.4,
   21.4,
   20.6,
   20.9,
   20.0,
   18.5,
   17.5,
   17.7,
   18.1,
   19.3,
   19.7,
   20.6,
   20.5,
   20.6,
   20.7,
   20.4,
   19.9,
   19.4,
   18.7,
   18.0,
   17.2,
   16.5,
   16.2,
   15.7,
   15.1,
   14.4,
   13.5,
   13.0,
   12.5,
   12.8,
   13.6,
   15.0,
   16.2,
   17.5,
   18.3,
   18.7,
   18.8,
   19.2,
   19.3,
   18.9,
   18.6,
   17.9,
   17.0,
   16.4,
   15.4,
   14.4,
   14.0,
   13.7,
   13.6,
   13.4,
   13.1,
   13.0,
   12.9,
   13.2,
   14.3,
   15.7,
   17.4,
   19.0,
   20.0,
   20.8,
   21.0,
   21.4,
   21.6,
   21.4,
   20.6,
   19.4,
   18.6,
   17.9,
   17.1,
   16.1,
   15.1,
   14.2,
   13.8,
   13.6,
   13.8,
   13.6,
   13.0,
   13.3,
   14.7,
   16.4,
   18.0,
   19.6,
   20.5,
   20.7,
   20.9,
   21.0,
   21.0,
   20.8,
   20.2,
   18.9,
   18.1,
   17.3,
   16.7,
   16.3,
   16.0,
   15.8,
   15.6,
   15.5,
   15.4,
   15.3,
   15.2,
   15.2,
   15.6,
   16.2,
   16.7,
   17.0,
   17.3,
   17.5,
   17.6,
   17.5,
   17.4,
   17.2,
   16.8,
   16.6,
   16.5,
   16.5,
   16.5,
   16.5,
   16.5,
   16.4,
   16.3,
   16.2,
   16.1,
   15.9,
   15.8,
   15.8,
   16.3,
   17.0,
   17.8,
   18.8,
   19.9,
   20.7,
   21.1,
   21.2,
   21.1,
   20.6,
   19.8,
   19.0,
   18.1,
   17.2,
   16.5,
   16.2,
   16.2,
   16.2,
   16.2,
   16.2,
   16.3,
   16.2,
   16.0,
   16.4,
   17.8,
   19.6,
   21.0,
   21.4,
   21.3,
   21.3,
   21.9,
   22.6,
   22.9,
   22.7,
   22.1,
   21.3,
   20.3,
   19.2,
   18.1,
   17.1,
   16.2],
  'relative_humidity_2m': [59,
   62,
   64,
   68,
   70,
   70,
   70,
   65,
   62,
   52,
   47,
   48,
   46,
   43,
   41,
   39,
   41,
   47,
   51,
   53,
   56,
   60,
   63,
   65,
   68,
   68,
   69,
   73,
   72,
   72,
   73,
   75,
   83,
   79,
   71,
   59,
   53,
   55,
   50,
   45,
   41,
   57,
   70,
   71,
   71,
   77,
   79,
   82,
   81,
   82,
   81,
   82,
   84,
   85,
   83,
   75,
   72,
   72,
   67,
   55,
   51,
   54,
   48,
   44,
   44,
   47,
   54,
   59,
   68,
   73,
   78,
   81,
   83,
   86,
   87,
   88,
   86,
   86,
   85,
   78,
   72,
   65,
   55,
   47,
   46,
   47,
   47,
   48,
   52,
   67,
   64,
   68,
   70,
   76,
   75,
   74,
   78,
   77,
   78,
   77,
   78,
   79,
   78,
   79,
   75,
   63,
   58,
   59,
   49,
   47,
   46,
   50,
   60,
   63,
   73,
   72,
   73,
   75,
   76,
   79,
   79,
   78,
   73,
   75,
   77,
   79,
   79,
   76,
   74,
   68,
   64,
   60,
   59,
   58,
   57,
   75,
   77,
   71,
   85,
   86,
   80,
   83,
   79,
   75,
   76,
   78,
   77,
   78,
   80,
   81,
   78,
   76,
   69,
   62,
   61,
   51,
   54,
   55,
   54,
   81,
   69,
   71,
   68,
   66,
   72,
   69,
   71,
   73,
   75,
   79,
   80,
   78,
   81,
   82,
   79,
   76,
   69,
   55,
   47,
   45,
   43,
   43,
   39,
   42,
   41,
   44,
   46,
   49,
   53,
   65,
   76,
   80,
   84,
   78,
   74,
   75,
   77,
   79,
   78,
   74,
   70,
   66,
   67,
   71,
   78,
   72,
   69,
   62,
   66,
   69,
   67,
   68,
   73,
   75,
   76,
   76,
   78,
   82,
   84,
   87,
   88,
   88,
   84,
   78,
   71,
   62,
   59,
   55,
   52,
   48,
   43,
   42,
   42,
   45,
   48,
   57,
   62,
   69,
   70,
   69,
   65,
   65,
   64,
   66,
   63,
   68,
   70,
   70,
   66,
   61,
   56,
   48,
   42,
   40,
   41,
   40,
   40,
   42,
   40,
   43,
   47,
   54,
   59,
   63,
   70,
   79,
   78,
   80,
   83,
   89,
   88,
   82,
   73,
   62,
   48,
   43,
   41,
   40,
   39,
   38,
   40,
   40,
   43,
   50,
   52,
   58,
   61,
   63,
   64,
   64,
   66,
   68,
   68,
   69,
   68,
   62,
   55,
   50,
   44,
   39,
   35,
   36,
   35,
   34,
   34,
   38,
   44,
   48,
   50,
   52,
   57,
   62,
   65,
   66,
   65,
   62,
   65,
   72,
   75,
   74,
   71,
   67,
   62,
   58,
   56,
   58,
   56,
   56,
   56,
   63,
   69,
   72,
   75,
   77,
   78,
   79,
   79,
   79,
   79,
   80,
   82,
   85,
   86,
   85,
   83,
   81,
   80,
   78,
   78,
   78,
   79,
   81,
   85,
   90,
   93,
   94,
   93,
   93,
   93,
   94,
   94,
   94,
   94,
   94,
   94,
   94,
   92,
   87,
   80,
   73,
   68,
   64,
   61,
   59,
   59,
   60,
   63,
   68,
   73,
   77,
   81,
   84,
   86,
   88,
   88,
   87,
   85,
   84,
   86,
   88,
   88,
   83,
   75,
   69,
   69,
   71,
   72,
   71,
   69,
   68,
   70,
   73,
   77,
   81,
   85,
   87,
   86,
   84],
  'wind_speed_10m': [9.0,
   9.0,
   11.4,
   10.4,
   10.0,
   10.3,
   12.1,
   12.9,
   14.9,
   16.6,
   16.1,
   20.5,
   19.5,
   20.4,
   19.0,
   17.6,
   17.6,
   13.7,
   10.6,
   7.9,
   11.9,
   8.7,
   5.8,
   4.6,
   7.1,
   6.3,
   5.5,
   3.6,
   4.8,
   3.8,
   7.1,
   8.4,
   8.6,
   8.6,
   10.6,
   15.3,
   15.8,
   15.3,
   14.1,
   18.1,
   16.0,
   21.6,
   16.3,
   12.0,
   14.0,
   12.7,
   12.6,
   12.8,
   11.9,
   13.4,
   13.2,
   14.2,
   13.7,
   13.6,
   15.7,
   17.3,
   16.2,
   15.0,
   15.2,
   16.2,
   15.5,
   15.5,
   15.5,
   12.6,
   11.9,
   13.7,
   15.1,
   13.7,
   12.7,
   11.2,
   9.4,
   8.8,
   5.8,
   6.1,
   6.8,
   4.5,
   6.5,
   6.2,
   5.6,
   5.4,
   6.0,
   8.0,
   10.2,
   10.7,
   10.1,
   10.1,
   10.1,
   8.7,
   8.3,
   4.4,
   2.6,
   4.5,
   5.1,
   5.9,
   4.2,
   5.5,
   5.5,
   5.1,
   5.5,
   5.8,
   5.4,
   5.2,
   5.8,
   7.1,
   7.8,
   11.3,
   13.0,
   13.0,
   16.3,
   16.9,
   18.5,
   16.7,
   13.9,
   16.5,
   14.3,
   11.1,
   12.0,
   12.1,
   14.1,
   12.7,
   11.1,
   11.1,
   13.1,
   10.9,
   9.2,
   10.2,
   10.0,
   11.5,
   13.5,
   16.1,
   16.3,
   19.9,
   19.3,
   22.3,
   21.7,
   22.0,
   20.2,
   19.9,
   15.3,
   16.3,
   16.9,
   17.4,
   15.8,
   14.9,
   15.5,
   15.5,
   17.4,
   17.1,
   15.9,
   14.3,
   14.4,
   16.1,
   18.9,
   18.6,
   20.5,
   22.0,
   22.3,
   22.4,
   22.0,
   15.2,
   19.8,
   17.3,
   17.3,
   18.6,
   13.3,
   17.4,
   14.8,
   15.6,
   13.7,
   14.2,
   14.8,
   15.5,
   14.2,
   12.8,
   12.3,
   13.3,
   12.7,
   13.4,
   15.3,
   16.5,
   13.1,
   11.9,
   11.8,
   10.8,
   7.2,
   6.9,
   3.6,
   1.5,
   2.8,
   4.3,
   3.6,
   5.4,
   5.4,
   6.0,
   7.2,
   7.2,
   7.5,
   8.4,
   7.6,
   8.9,
   10.4,
   10.5,
   10.1,
   11.6,
   10.6,
   10.4,
   11.8,
   12.2,
   11.9,
   10.8,
   10.0,
   9.0,
   8.5,
   7.6,
   7.7,
   6.2,
   5.5,
   6.6,
   6.6,
   5.4,
   5.4,
   3.3,
   5.4,
   3.8,
   4.7,
   4.9,
   6.9,
   9.3,
   12.5,
   10.0,
   9.7,
   11.3,
   8.6,
   2.8,
   6.0,
   6.3,
   6.6,
   6.5,
   5.9,
   7.9,
   10.9,
   8.9,
   8.0,
   6.3,
   13.0,
   14.8,
   19.1,
   19.3,
   15.5,
   15.3,
   14.4,
   14.9,
   16.3,
   16.0,
   14.2,
   16.1,
   13.4,
   11.3,
   11.0,
   11.5,
   10.2,
   12.6,
   10.8,
   12.8,
   13.6,
   15.8,
   16.3,
   12.1,
   10.4,
   9.8,
   10.5,
   11.5,
   12.6,
   14.1,
   13.2,
   14.2,
   12.4,
   14.9,
   13.5,
   13.2,
   12.2,
   8.1,
   5.2,
   1.1,
   2.6,
   3.1,
   3.9,
   2.8,
   4.1,
   2.4,
   3.8,
   4.2,
   4.6,
   5.9,
   5.4,
   5.2,
   6.0,
   6.6,
   6.9,
   10.0,
   8.5,
   9.3,
   6.9,
   5.6,
   6.5,
   5.2,
   2.5,
   0.8,
   1.5,
   0.7,
   0.8,
   1.6,
   1.8,
   1.6,
   2.4,
   2.6,
   3.4,
   3.2,
   3.2,
   4.0,
   4.5,
   4.8,
   7.4,
   7.6,
   9.0,
   7.6,
   8.8,
   6.7,
   5.6,
   3.4,
   4.1,
   4.0,
   3.7,
   3.7,
   3.7,
   3.5,
   3.1,
   2.1,
   0.7,
   1.0,
   0.5,
   2.2,
   3.6,
   3.9,
   4.3,
   5.1,
   6.1,
   7.5,
   8.4,
   8.7,
   8.4,
   8.3,
   8.1,
   8.4,
   8.6,
   8.0,
   7.2,
   6.7,
   6.9,
   7.6,
   8.0,
   8.4,
   8.5,
   8.6,
   8.0,
   7.3,
   6.6,
   6.5,
   6.8,
   7.2,
   8.0,
   8.7,
   9.3,
   8.6,
   8.0,
   6.5,
   4.0,
   1.6,
   1.8,
   3.1,
   3.4,
   4.1,
   4.5,
   4.7,
   4.7,
   5.1,
   5.4,
   5.6,
   5.2,
   4.3,
   4.6,
   5.9,
   8.2,
   9.8,
   10.3,
   10.7,
   10.3,
   8.9,
   6.9,
   6.7,
   8.2,
   10.8,
   12.2,
   11.3,
   10.1,
   10.9,
   11.5,
   11.4]}}

In [52]:
df=pd.DataFrame(data)
df.head(10)

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,52.52,13.419998,3.095508,0,GMT,GMT,38.0,iso8601,"[2026-08-30T00:00, 2026-08-30T01:00, 2026-08-3..."
temperature_2m,52.52,13.419998,3.095508,0,GMT,GMT,38.0,°C,"[20.0, 19.8, 19.5, 19.3, 19.3, 19.3, 19.4, 20...."
relative_humidity_2m,52.52,13.419998,3.095508,0,GMT,GMT,38.0,%,"[59, 62, 64, 68, 70, 70, 70, 65, 62, 52, 47, 4..."
wind_speed_10m,52.52,13.419998,3.095508,0,GMT,GMT,38.0,km/h,"[9.0, 9.0, 11.4, 10.4, 10.0, 10.3, 12.1, 12.9,..."

In [53]:
df = pd.DataFrame(data["hourly"])

In [54]:
df["latitude"] = data["latitude"]
df["longitude"] = data["longitude"]
df["elevation"] = data["elevation"]
df["timezone"] = data["timezone"]
df["timezone_abbreviation"] = data["timezone_abbreviation"]

In [55]:
df["time"] = pd.to_datetime(df["time"])

In [56]:
units = data["hourly_units"]

In [57]:
#Actual data
df

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,latitude,longitude,elevation,timezone,timezone_abbreviation
0,2026-08-30 00:00:00,20.0,59,9.0,52.52,13.419998,38.0,GMT,GMT
1,2026-08-30 01:00:00,19.8,62,9.0,52.52,13.419998,38.0,GMT,GMT
2,2026-08-30 02:00:00,19.5,64,11.4,52.52,13.419998,38.0,GMT,GMT
3,2026-08-30 03:00:00,19.3,68,10.4,52.52,13.419998,38.0,GMT,GMT
4,2026-08-30 04:00:00,19.3,70,10.0,52.52,13.419998,38.0,GMT,GMT
...,...,...,...,...,...,...,...,...,...
403,2026-09-15 19:00:00,20.3,81,11.3,52.52,13.419998,38.0,GMT,GMT
404,2026-09-15 20:00:00,19.2,85,10.1,52.52,13.419998,38.0,GMT,GMT
405,2026-09-15 21:00:00,18.1,87,10.9,52.52,13.419998,38.0,GMT,GMT
406,2026-09-15 22:00:00,17.1,86,11.5,52.52,13.419998,38.0,GMT,GMT
407,2026-09-15 23:00:00,16.2,84,11.4,52.52,13.419998,38.0,GMT,GMT

In [58]:
# meta data
units

{'time': 'iso8601',
 'temperature_2m': '°C',
 'relative_humidity_2m': '%',
 'wind_speed_10m': 'km/h'}

In [59]:
#Validation
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   time                   408 non-null    datetime64[us]
 1   temperature_2m         408 non-null    float64
 2   relative_humidity_2m   408 non-null    int64
 3   wind_speed_10m         408 non-null    float64
 4   latitude               408 non-null    float64
 5   longitude              408 non-null    float64
 6   elevation              408 non-null    float64
 7   timezone               408 non-null    str
 8   timezone_abbreviation  408 non-null    str
dtypes: datetime64[us](1), float64(5), int64(1), str(2)
memory usage: 28.8 KB

In [60]:
df.duplicated().sum()

np.int64(0)

In [61]:
df.describe()

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,latitude,longitude,elevation
count,408,408.000000,408.000000,408.000000,4.080000e+02,4.080000e+02,408.0
mean,2026-09-07 11:30:00,18.360784,67.360294,9.910049,5.252000e+01,1.342000e+01,38.0
min,2026-08-30 00:00:00,12.200000,34.000000,0.500000,5.252000e+01,1.342000e+01,38.0
25%,2026-09-03 05:45:00,16.100000,57.000000,5.800000,5.252000e+01,1.342000e+01,38.0
50%,2026-09-07 11:30:00,17.950000,70.000000,9.300000,5.252000e+01,1.342000e+01,38.0
75%,2026-09-11 17:15:00,20.500000,78.000000,13.625000,5.252000e+01,1.342000e+01,38.0
max,2026-09-15 23:00:00,28.500000,94.000000,22.400000,5.252000e+01,1.342000e+01,38.0
std,NaN,3.224992,14.615467,5.017813,1.422830e-14,3.557076e-15,0.0

In [62]:
df.columns

Index(['time', 'temperature_2m', 'relative_humidity_2m', 'wind_speed_10m',
       'latitude', 'longitude', 'elevation', 'timezone',
       'timezone_abbreviation'],
      dtype='str')

In [65]:
df.dtypes

time                     datetime64[us]
temperature_2m                  float64
relative_humidity_2m              int64
wind_speed_10m                  float64
latitude                        float64
longitude                       float64
elevation                       float64
timezone                            str
timezone_abbreviation               str
dtype: object

In [67]:
df.to_csv('weather_data.csv')

In [68]:
#load into PostagresSQL DB

In [69]:
engine=create_engine(
    "postgresql+psycopg2://postgres:root@localhost:5432/Weather"
    )
df2 = pd.read_csv("weather_data.csv")

In [70]:
df2.to_sql(
    "weather_data",
    engine,
    if_exists="append",
    index=False
    )

408